# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imcui.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(732, 550)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(270, 50, 161, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(180, 160, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(170, 220, 101, 31))
        self.label_3.setObjectName("label_3")
        self.indice = QtWidgets.QLabel(Dialog)
        self.indice.setGeometry(QtCore.QRect(230, 360, 141, 61))
        self.indice.setObjectName("indice")
        self.vpoid = QtWidgets.QTextEdit(Dialog)
        self.vpoid.setGeometry(QtCore.QRect(310, 150, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.vpoid.setFont(font)
        self.vpoid.setObjectName("vpoid")
        self.vtaille = QtWidgets.QTextEdit(Dialog)
        self.vtaille.setGeometry(QtCore.QRect(310, 220, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.vtaille.setFont(font)
        self.vtaille.setObjectName("vtaille")
        self.btn = QtWidgets.QPushButton(Dialog)
        self.btn.setGeometry(QtCore.QRect(330, 320, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn.setFont(font)
        self.btn.setObjectName("btn")
        self.erreur = QtWidgets.QLabel(Dialog)
        self.erreur.setGeometry(QtCore.QRect(360, 270, 91, 31))
        self.erreur.setObjectName("erreur")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#5500ff;\">Calcule de IMC</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Poid (Kg)</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Taille (m)</span></p></body></html>"))
        self.indice.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Votre imc est</span></p></body></html>"))
        self.vpoid.setPlaceholderText(_translate("Dialog", "Exemple 80.2"))
        self.vtaille.setPlaceholderText(_translate("Dialog", "exemple 1.70"))
        self.btn.setText(_translate("Dialog", "Calculer"))
        self.erreur.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
